blog/urls.py
from django.urls import path
from .views import home_page, contact_us, blog_detail, what_is_armath, edu_program, why_armath

app_name = "blog"
urlpatterns = [
    path('', home_page, name="home"),
    path('contact-us/', contact_us,name="contact-us"),
    path('blog-detail/<int:pk>/', blog_detail, name="blog-detail"),
    path('what-is-armath/', what_is_armath,name="what-is-armath"),
    path('edu-program/', edu_program,name="edu-program"),
    path('why-armath/', why_armath,name="why-armath")
]

ctblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):

    title = models.CharField(max_length=255)
    description = models.TextField()
    price = models.CharField(max_length=11)
    image1 = models.ImageField(upload_to="blog_posts/", default=None, null=True, blank=True)
    image2 = models.ImageField(upload_to="blog_posts/", default=None, null=True, blank=True)
    image3 = models.ImageField(upload_to="blog_posts/", default=None, null=True, blank=True)

    def __str__(self):
        return self.title

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name + " | "+ self.last_name + " | " + self.email

class Comment(models.Model):
    blog = models.ForeignKey(Blog, related_name="blog_comment", on_delete=models.CASCADE)
    name = models.CharField(max_length = 255)
    message = models.TextField()

    def __str__(self):
        return self.blog.title + " - "+self.message

blog/forms.py
from django import forms
from .models import Contact, Comment


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = "__all__"

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ["blog"]

blog/views.py
from django.shortcuts import render
from .models import Blog, Contact, Comment
from .forms import ContactForm, CommentForm
# Create your views here.

def home_page(request):
    context = {}
    blogs = Blog.objects.all()
    context["blogs"] = blogs

    return render(request, "home.html", context)

def contact_us(request):
    context = {}
    if request.POST:
        my_form = ContactForm(request.POST)
        if my_form.is_valid():
            my_form.save()
        else:
            context["errors"] = my_form.errors
     
    return render(request, "contact_us.html",context)

def blog_detail(request, pk):
    context= {}
    blog = Blog.objects.get(id=pk)
    context['blog'] = blog

    if request.POST:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            obj = comment_form.save(commit=False)
            obj.blog = context["blog"]
            obj.save()
        else:
            context["errors"] = comment_form.errors

    comments = Comment.objects.filter(blog = context['blog'])
    context['comments'] = comments
    return render(request, "blog_detail.html", context)

def what_is_armath(request):

    return render(request, "About/what_is_armath.html",{})

def edu_program(request):

    return render(request, "About/edu_prog.html",{})

def why_armath(request):

    return render(request, "About/why_armath.html",{})

blog/templates/About/edu_prog.html
{% extends 'base.html' %}

{%block nav-about%}
<li class="nav-item dropdown active">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      About
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="{%url 'blog:what-is-armath'%}">What is Armath</a>
      <a class="dropdown-item active" href="{%url 'blog:edu-program'%}">Educational program</a>
      <a class="dropdown-item" href="{%url 'blog:why-armath'%}">WhyArmath</a>
    </div>
  </li>
{%endblock%}

{% block content %}
<div class="main">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem reiciendis, architecto fugiat dolore corporis dicta esse error in atque hic, molestiae laboriosam eveniet tenetur repudiandae ab! Dicta ut eius corrupti.</p>
</div>
{% endblock %}

blog/templates/About/what_is_armath.html
{% extends 'base.html' %}

{%block nav-about%}
<li class="nav-item dropdown active">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      About
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item active" href="{%url 'blog:what-is-armath'%}">What is Armath</a>
      <a class="dropdown-item" href="{%url 'blog:edu-program'%}">Educational program</a>
      <a class="dropdown-item" href="{%url 'blog:why-armath'%}">WhyArmath</a>
    </div>
  </li>
{%endblock%}

{%block content%}

<input type="text" name="" id="input" placeholder="Enter the Number">
<br>

<button onclick="myFunction()">Submit</button>
<br>

<h1 id="title"></h1>
<p id="demo"></p>

{%endblock%}

blog/templates/About/why_armath.html
{% extends 'base.html' %}

{%block nav-about%}
<li class="nav-item dropdown active">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      About
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="{%url 'blog:what-is-armath'%}">What is Armath</a>
      <a class="dropdown-item" href="{%url 'blog:edu-program'%}">Educational program</a>
      <a class="dropdown-item active" href="{%url 'blog:why-armath'%}">WhyArmath</a>
    </div>
  </li>
{%endblock%}


{% block content %}
<div class="main">
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos inventore qui aut excepturi sed officiis tempore exercitationem, consequatur reiciendis possimus aliquam! Repellendus saepe placeat dolorum expedita ipsa debitis esse itaque.</p>
</div>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
<head>
    <link href="https://fonts.googleapis.com/css?family=Bentham|Playfair+Display|Raleway:400,500|Suranna|Trocchi" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{%static 'style.css'%}">
    <link rel="shortcut icon" href="https://armath.am/assets/images/armath_favicon.ico">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  <div class="navbar-div">
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{%url 'blog:home'%}">Armath</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {%block nav-home%}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'blog:home'%}">Home <span class="sr-only">(current)</span></a>
          </li>
          {%endblock%}

          {%block nav-about%}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              About
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{%url 'blog:what-is-armath'%}">What is Armath</a>
              <a class="dropdown-item" href="{%url 'blog:edu-program'%}">Educational program</a>
              <a class="dropdown-item" href="{%url 'blog:why-armath'%}">WhyArmath</a>
            </div>
          </li>
          {%endblock%}
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Franchise model
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{%url 'blog:what-is-armath'%}">Franchising Model</a>
              <a class="dropdown-item" href="{%url 'blog:what-is-armath'%}">Budget</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Become a partner
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{%url 'blog:what-is-armath'%}">How to start?</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{%url 'blog:what-is-armath'%}">Represent Armath in your country</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{%url 'blog:what-is-armath'%}">Become a franchisee</a>
            </div>
          </li>
          {%block nav-contact-us%}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'blog:contact-us'%}">Contact <span class="sr-only">(current)</span></a>
          </li>
          {%endblock%}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    
  <div class="main">
    {%block content%}

    {%endblock%}
  </div>
</div>
      <div class="footer">
          <!-- Footer -->
<footer class="page-footer font-small mdb-color pt-4">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">
  
      <!-- Footer links -->
      <div class="row text-center text-md-left mt-3 pb-3">
  
        <!-- Grid column -->
        <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Armath</h6>
          <p class="footer_text"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad repudiandae explicabo a delectus, quo voluptatum minima ex animi nemo quam cum pariatur, eum ducimus aperiam alias reiciendis voluptas velit quaerat.</p>
        </div>
        <!-- Grid column -->
  
        <hr class="w-100 clearfix d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
          <p>
            <a class="footer_links" href="#!">Լաբորատորիաներ</a>
          </p>
          <p>
            <a class="footer_links" href="#!">Էլ․ուսուցում</a>
          </p>
          <p>
            <a class="footer_links" href="#!">Միջոցառումներ</a>
          </p>
          <p>
            <a class="footer_links" href="#!">Նորություններ</a>
          </p>
        </div>
        <!-- Grid column -->
  
        <hr class="w-100 clearfix d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
          <p>
            <a class="footer_links" href="https://facebook.com">Գործընկերներ</a>
          </p>
          <p>
            <a class="footer_links" href="#!">Ձեռքբերումներ</a>
          </p>
          <p>
            <a class="footer_links" href="#!">Նվիրաբերել</a>
          </p>
          <p>
            <a class="footer_links" href="#!">Աշխատանք</a>
          </p>
        </div>
  
        <!-- Grid column -->
        <hr class="w-100 clearfix d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
          <p class="footer_text" > 
            <i class="fa fa-home mr-3"></i>Հակոբ Հակոբյան, 3 Երևան</p>
          <p class="footer_text" >
            <i class="fa fa-envelope mr-3"></i> info@armath.com</p>
          <p class="footer_text" >
            <i class="fa fa-phone mr-3"></i>+374 11 548881</p>
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Footer links -->
  
      <hr>
  
      <!-- Grid row -->
      <div class="row d-flex align-items-center">
  
        <!-- Grid column -->
        <div class="col-md-7 col-lg-8">
  
          <!--Copyright-->
          <p class="text-center text-md-left footer_text">© 2020 Copyright:
            <a class="armath_link" href="https://armath.am/hy" target="_blank">
              <strong> Armath.am</strong>
            </a>
          </p>
  
        </div>
        <!-- Grid column -->
  
        <!-- Grid column -->
        <div class="col-md-5 col-lg-4 ml-lg-0">
  
          <!-- Social buttons -->
          <div class="text-center text-md-right">
            <ul class="list-unstyled list-inline">
              <li class="list-inline-item">
                <a href="" class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-youtube fa-stack-1x fa-inverse"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="" class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="" class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="" class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                </a>
              </li>
            </ul>
          </div>
  
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
  
    </div>
    <!-- Footer Links -->
  
  </footer>
  <!-- Footer -->
      </div>

  <script src="{%static 'js/main.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog_detail.html
{% extends 'base.html' %}

{% block content %}
<body class="detail_body">
  <div class="blog-carousel">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="width: 100%;">
      {% if not blog.image2 %}

      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100 image-resize" src="{{blog.image1.url}}" alt="">
        </div>
      </div>

      {%elif not blog.image3%}
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100 image-resize" src="{{blog.image1.url}}" alt="">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100 image-resize" src="{{blog.image2.url}}" alt="">
        </div>

        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      {% else %}
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <h2 style="text-align: center;"><i>{{blog.title}}</i></h2>
        <div class="carousel-item active">
          <img class="d-block w-100 image-resize" src="{{blog.image1.url}}" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100 image-resize" src="{{blog.image2.url}}" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100 image-resize" src="{{blog.image3.url}}" alt="Third slide">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

      {% endif %}
    </div>
  </div>

  <div class="card-body">
    <h5 class="card-title">{{blog.title}}</h5>
    <p class="card-text">{{blog.description}}</p>
    <p class="card-text"><small class="text-muted">{{blog.price}} $</small></p>
  </div>
  
  <br>
  <h3>Comments</h3>
  <hr>
  {%for comment in comments%}
  <p><b>{{comment.name}}</b></p>
  <p>{{comment.message}}</p>
  <hr>
  {%endfor%}

  <div class="div_comment" style="text-align: center;">
  <form class="single_comment_form" action="" method="POST">
      {%csrf_token%}
      <input  type="text" placeholder="Your Name" name="name" class="message_comment form-control md-textarea" required="" autofocus="">
      <br>

      <textarea class="message_comment form-control md-textarea" placeholder="Write Your Comment" name="message" id="" cols="30" rows="10" required="" style="height: 110px;"></textarea>
      <br>

      <button class="btn btn-primary">Submit</button>
      <br>
  </form>
  </div>
</body>

{% endblock %}

blog/templates/contact_us.html
{% extends 'base.html' %}

{%block nav-contact-us%}
<li class="nav-item active">
  <a class="nav-link active" href="{%url 'blog:contact-us'%}">Contact<span class="sr-only">(current)</span></a>
</li>
{%endblock%}

{%block content%}
<body class="body_contact">
  <div class="main_conatct">
    <!-- Section: Contact v.1 -->
  <section class="my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold text-center my-5">Contact us</h2>
  <!-- Section description -->
  <p class="text-center w-responsive mx-auto pb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
  Fugit, error amet numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum quisquam
  eum porro a pariatur veniam.</p>

  <!-- Grid row -->
  <div class="row">

  <!-- Grid column -->
  <div class="col-lg-5 mb-lg-0 mb-4">

  <!-- Form with header -->
  <div class="card">
    <div class="card-body">
      <!-- Header -->
      <div class="form-header blue accent-1">
        <h3 class="mt-2"><i class="fa fa-envelope mt-2"></i> Write to us:</h3>
      </div>
      <p class="white-text">We'll write rarely, but only the best content.</p>
      <!-- Body -->
      <form method="post" action="">{%csrf_token%}
      <div class="md-form">
        <i class="fa fa-user prefix contact_icons"></i>
        <label class="white-text" for="form-name">First Name</label>
        <input placeholder="FirstName" type="text" id="form-name" class="form-control" name="first_name" required="" autofocus=""> 
      </div>
      <div class="md-form">
        <i class="fa fa-user prefix contact_icons"></i>
        <label class="white-text" for="form-name">Last Name</label>
        <input placeholder="Last Name" type="text" id="form-name" class="form-control" name="last_name" required="" autofocus="">  
      </div>
      <div class="md-form">
        <i class="fa fa-envelope prefix contact_icons"></i>
        <label class="white-text" for="form-email">Your email</label>
        <input placeholder="example@mail.ru" type="email" id="form-email" class="form-control" name="email" required="" autofocus="">
        <h6 class="errors">{%if errors%} {{errors.email}} {%endif%}</h6>
      </div>
      <div class="md-form">
        <i class="fa fa-pencil prefix contact_icons"></i>
        <label class="white-text" for="form-text">Send message</label>
        <textarea name="message" placeholder="Insert the Message" id="form-text" class="form-control md-textarea" rows="3" required="" autofocus=""></textarea>
      </div>
      <div class="text-center">
        <button class="btn btn-dark message_send_button">Submit</button>
      </div>
      </form>
    </div>
  </div>
  <!-- Form with header -->

  </div>
  <!-- Grid column -->

  <!-- Grid column -->
  <div class="col-lg-7">

  <!--Google map-->
  <div id="map-container-section" class="z-depth-1-half map-container-section mb-4" style="height: 400px">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3042.754152069794!2d44.27601641473192!3d40.303417370448315!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x406a8f013b352641%3A0xde52692a7c0be9b9!2zQXJtYXRoIEVuZ2luZWVyaW5nIExhYiBBZ2FyYWsvINSx1oDVtNWh1akg1avVttWq1aXVttWl1oDVodWv1aHVtiDVrNWh1aLVuNaA1aHVv9W41oDVq9WhINSx1LPUsdWQ1LHUvw!5e0!3m2!1sen!2sus!4v1587575348847!5m2!1sen!2sus" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
  </div>
  <!-- Buttons-->
  <div class="row text-center">
    <div class="col-md-4">
      <a class="btn-floating blue accent-1">
        <i class="fa fa-map contact_icons"></i>
      </a>
      <p class="mb-md-0">New York, 94126</p>
      <p class="mb-md-0">United States</p>
    </div>
    <div class="col-md-4">
      <a class="btn-floating blue accent-1">
        <i class="fa fa-phone contact_icons"></i>
      </a>
      <p class="mb-md-0">+374 11 548881</p>
      <p class="mb-md-0">Mon - Fri, 8:00-22:00</p>
    </div>
    <div class="col-md-4">
      <a class="btn-floating blue accent-1">
        <i class="fa fa-envelope contact_icons"></i>
      </a>
      <p class="mb-md-0">info@armath.com</p>
      <p class="mb-md-0">sale@gmail.com</p>
    </div>
  </div>

  </div>
  <!-- Grid column -->

  </div>
  <!-- Grid row -->
</body>
{%endblock%}

blog/templates/home.html
{% extends 'base.html' %}

{%block nav-home%}
<li class="nav-item active">
  <a class="nav-link active" href="{%url 'blog:home'%}">Home <span class="sr-only">(current)</span></a>
</li>
{% endblock %}

{% block content %}

<body class="home-body">
  {% for blog in blogs %}
  <div class="wrapper">
    <div class="product-img">
      {% if blog.image1 %}
      <a href="{%url 'blog:blog-detail' pk=blog.id %}"><img src="{{blog.image1.url}}"  height="420" width="327"></a>
      {% endif %}
    </div>
    <div class="product-info">
      <div class="product-text">
        <h1>{{blog.title}}</h1>
        <h2>by studio and friends</h2>
        <p>{{ blog.description }}</p>
      </div>
      <div class="product-price-btn">
        <!-- <p class="price"><span>{{ blog.price }}</span>$</p> -->
        <a href="{%url 'blog:blog-detail' pk=blog.id %}"><button type="button">buy now</button></a>
      </div>
    </div>
  </div>
  {%endfor%}

</body>

{% endblock %}